title: CoCoML
description: The documentation for a concise and consistent modeling language.
theme: just-the-docs

url: https://gfse.github.io/CoCoML

aux_links:
  Home: https://github.com/gfse/CoCoML
