title: CoCoML
description: The documentation for a concise and consistent modeling language.
theme: just-the-docs

url: https://gfse.github.io/CoCoML

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
